version: '3'
services:
  app:
    image: nginx:latest
    container_name: Kuedro
    working_dir: /usr/share/nginx/html
    volumes:
      - /share/Web/Kuedro:/usr/share/nginx/html/kuedro      
    ports:
      - "32768:80"
    # IMPORTANTE: Aggiungi 'sh' prima del percorso
    command: sh kuedro/genesis.sh
    restart: always