name: SQLServer

on: [ push ]

jobs:
  jobs:
    runs-on: ubuntu-latest
    
    name: SQL DB
    env:
      
      DB_DATABASE: all
      DB_HOST: localhost

    steps:
      - run: |
          sudo /etc/init.d/mysql start
              
  test:
    runs-on: ubuntu-latest    
    name: SQL DB TEST    
    steps:
      - run: |
          echo "test";|
          sudo /etc/init.d/mysql status;
