name: SQLServer

on: [ push ]

jobs:
  jobs:
    runs-on: ubuntu-latest
    
    name: SQL DB
    env:
      
      DB_DATABASE: all
      DB_HOST: localhost

    steps:
      - run: |
         echo $CODESPACE_NAME> .codespaceMTC;
         echo $CODESPACE_NAME;
         cat .codespaceMTC;
  test:
    runs-on: ubuntu-latest    
    name: UPDATE CODESPACE TEST    
    steps:
      - run: |
         echo $CODESPACE_NAME;
