name: SQLServer

on: [ push ]

jobs:
  jobs:
    runs-on: ubuntu-latest
    
    name: SQL DB
    env:
      
      DB_DATABASE: all
      DB_HOST: localhost

    steps:
      - run: |
         echo $CODESPACE_NAME> .codespace;        
              cat .codespace;
  test:
    runs-on: ubuntu-latest    
    name: UPDATE CODESPACE TEST    
    steps:
      - run: |
         cat .codespace;
